version: "3.8"

services:
  frontend:
    build: ./tvm
    image: tvm
    command: sh -c "yarn --dev && yarn dev"
    volumes:
      - ./tvm:/usr/app
      - ./tvm/node_modules:/usr/app/node_modules
    ports:
      - "3000:80"
    environment:
      PORT: 80
